stages:
  - 🧹 lint

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit

default:
  image: python:3.10

  cache:
    paths:
      - .cache/
      - venv/

  before_script:
    - apt install git
    - python -V
    - python -m pip install -U virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m pip install -U pip
    - python -m pip install -U -r requirements.txt

git-hooks:
  stage: 🧹 lint
  tags:
    - docker
  rules:
    # on default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: always
    # on a MR if previous jobs are successful
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
  script:
    - pre-commit install
    - git fetch origin
    - pre-commit run --from-ref "origin/$CI_DEFAULT_BRANCH" --to-ref "$CI_COMMIT_SHA";
  allow_failure: true
