# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "node_modules|migrations|.venv|tests/dev/|tests/fixtures/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args:
          [
            "--config",
            ".markdownlint.json",
            "--ignore-path",
            ".markdownlintignore",
            "--fix",
            "content",
          ]
        language: node
        pass_filenames: true
        types: [file, markdown, non-executable]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.2.1"
    hooks:
      - id: ruff
        args: ["--fix-only", "--target-version=py39"]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ["--target-version=py39"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--config=api/setup.cfg"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.0.0-beta.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@8.18.0
          - eslint-plugin-react@7.30.0

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        entry: bash -c 'lst=$(git diff --name-only --cached HEAD | egrep ".(yml|yaml)"); if [ -n "$lst" ]; then ansible-lint $lst; fi'
