---
ansible_python_interpreter: "/usr/bin/python3"

# Github repository
## Repository URL
github_repo_url: https://github.com/asterscen74/bivouac.git
## Repository main branch
github_repo_branch: main
## Repository output
github_repo_dir: /opt/bivouac

# PostgreSQL
pg_user: bivouac
pg_password: bivouac
pg_db: bivouac
pg_port: 5432
pg_host: localhost

## Nginx config
nginx_server_name: "bivouac.oslandia.io"
ssl_certificate: true
certbot_email1: "vincent.bre@oslandia.com"
certbot_email2: "sylvain.beorchia@oslandia.com"

# API
api_fastapi_server_host: bivouac.oslandia.io
api_fastapi_server_port: 9010

# React
front_port: 3010

# SMTP
smtp_port: 587
smtp_server: smtp.gmail.com
smtp_login: bivouac@cen-haute-savoie.org
smtp_password: kcrs sqoy lkrl rqsy
smtp_sender_email: bivouac@cen-haute-savoie.org
