import { createSlice } from "@reduxjs/toolkit";

export const about = createSlice({
    name: "about",
    initialState: {
        fr: `
        <p>Asters, le conservatoire d’espaces naturels de Haute-Savoie, accompagné des services de l’état et des acteurs du territoire haut-savoyard a développé une solution de gestion du bivouac face à l’augmentation de la fréquentation dans les réserves naturelles nationales. Un premier test en 2023 a été déployé sur le territoire de la Communauté de Communes Vallée de Chamonix Mont-Blanc. Suite à l’adhésion et aux résultats encourageants, l’outil continue son déploiement sur l’ensemble du département en 2024. </p>
        <p><strong>Contexte du projet :</strong></p>
        <p>La montagne et les espaces protégés sont des <strong>refuges</strong> pour la biodiversité autant que des espaces de <strong>ressourcement</strong> pour les visiteurs.</p>
        <p>Malheureusement, la présence massive et prolongée de randonneurs et de bivouaqueurs concourt à transformer durablement ces milieux naturels, préservés jusqu’alors. Des pics de fréquentation atteignant jusqu’à plus de 120 tentes au bord d’un lac d’altitude ont été constatés certains soirs par les gardes des réserves naturelles. </p>
        <p>Cette fréquentation entraîne de <strong>multiples impacts</strong> pour les nombreuses espèces rares et/ou protégées qui vivent dans ces réserves : nuisances sonores sources de stress et de modification des comportements ; abandons de déchets, toilettes sauvages, polluants dans les cours d’eau et lacs, perturbation des habitats remarquables…</p>
        <p>- <strong>Dégradation des sols</strong> : la fréquentation entraine une érosion des sentiers et la création de sentes parallèles qui nécessitent parfois la mise en œuvre de lourds chantiers de restauration. Les bivouaqueurs modifient le terrain de bivouac pour la nuit pour améliorer leur confort : terres aplanies, rochers déplacés. Ainsi, si chaque soir plus de 250 personnes (si nous reprenons l’exemple de 120 tentes) modifient l’environnement pour leur nuit, cela engendre de sérieux dommages. </p>
        <p>- <strong>Perturbation de la faune</strong> : En randonnant et bivouaquant dans un espace naturel protégé, vous pénétrez dans un monde fragile. Les animaux font face à des conditions de vie éprouvantes de haute montagne. Le bruit et le dérangement produits par les humains <strong>sont vécus comme autant d’alertes qui déclenchent potentiellement des</strong> dépenses énergétiques supplémentaires pour fuir. Le dérangement entraîne également des échecs de reproduction notamment par l’abandon de couvées ou de nichées.
        Ne serait-ce qu’une voix, un passage, une musique peut menacer la survie d’individus (oiseaux, mammifères). </p>
        <p>- <strong>Qualité des eaux des ruisseaux et des lacs</strong> : des berges foulées par des millions de visiteurs, de la crème solaire, des produits vaisselles… tout cela impacte irrémédiablement les cours d’eau et lacs d’altitudes. Une eau trouble nuit à l’oxygénation du milieu, pourtant vitale pour les organismes vivants qui sont également affaiblis par les polluants.</p>
        <p>- <strong>Toilettes sauvages et déchets</strong> : Les excréments humain sont parfois porteur de parasites destructeurs. Ils contribuent également à la pollution des rivières et des lacs. La décomposition des déchets, même biodégradables est très lente. Une pomme à 2000m d’altitude met plusieurs mois à se décomposer. Cela perturbe l’ensemble du cycle biologique. </p>
        <p>Admirons les fleurs de montagne sans les cueillir, marchons sur les sentiers balisés sans piétiner les milieux naturels alentour, refermons les barrières des pâturages pour respecter le travail des bergers.
        La nature est notre maison à tous, c’est un espace de vie pour la biodiversité et les animaux ainsi qu’un espace de travail. Nous sommes nombreux à la partager, chaque geste compte, alors passe le message à ton voisin !</p>
        `,
        en: `
        <p>Asters, the Conservatoire d'Espaces Naturels de Haute-Savoie (Haute-Savoie Nature Conservatory), together with government departments and local players, has developed a solution for managing bivouacs in the face of increasing visitor numbers in national nature reserves. An initial test in 2023 was deployed on the territory of the Communauté de Communes Vallée de Chamonix Mont-Blanc. Following the encouraging results, the tool will continue to be deployed throughout the departement in 2024. </p>
        <p><strong>Project background :</strong></p>
        <p>Mountains and protected areas are <strong>refuges</strong> for biodiversity as well as places where visitors can <strong>recharge</strong> their batteries.</p>
        <p>Unfortunately, the massive and prolonged presence of hikers and bivouacers is contributing to the long-term transformation of these previously unspoilt natural environments. Some evenings, nature reserve wardens have observed peaks of up to 120 tents on the banks of a high-altitude lake. </p>
        <p>This frequentation has <strong>multiple impacts</strong> on the many rare and/or protected species that live in these reserves: noise pollution, which causes stress and alters behavior; waste dumping, unauthorized toilets, pollutants in rivers and lakes, disturbance of remarkable habitats...</p>
        <p>- <strong>Soil degradation</strong>: visitor numbers lead to trail erosion and the creation of parallel paths, sometimes requiring major restoration work. Bivouac-goers modify the bivouac site for the night to improve their comfort: ground levelled, rocks moved. So, if every evening more than 250 people (if we take the example of 120 tents) modify the environment for their night, this causes serious damage. </p>
        <p>- <strong>Wildlife disturbance</strong>: When hiking and bivouacking in a protected natural area, you are entering a fragile world. Animals have to cope with the harsh living conditions of the high mountains. Noise and human disturbance <strong>are experienced as alarms, potentially triggering additional</strong> energy expenditure to escape. Disturbance also leads to reproductive failures, notably the abandonment of clutches or broods. Even a single voice, a passage or music can threaten the survival of individuals (birds, mammals).</p>
        <p>- <strong>Water quality in streams and lakes</strong>: banks trodden by millions of visitors, suntan lotion, dishwashing products... all these have an irreparable impact on mountain streams and lakes. Cloudy water impairs oxygenation, which is vital for living organisms that are also weakened by pollutants and inputs.</p>
        <p>- <strong>Toilets and waste</strong>: Human excrement can carry destructive parasites. It also contributes to the pollution of rivers and lakes. Even biodegradable waste decomposes very slowly. An apple at 2000m altitude takes several months to decompose. This disrupts the entire biological cycle. </p>
        <p>Let's admire mountain flowers without picking them, let's walk on marked trails without trampling on the surrounding natural environment, let's close pasture gates to respect the work of shepherds.
        Nature is our common home, a living space for biodiversity and animals, as well as a working space. Every gesture counts, so spread the word !</p>
        `,
        it: `
        <p>Asters, il Conservatoire d'Espaces Naturels de Haute-Savoie (autorità per la conservazione della natura dell'Alta Savoia), insieme ai dipartimenti governativi e agli attori locali, ha sviluppato una soluzione di gestione dei bivacchi per far fronte all'aumento del numero di visitatori nelle riserve naturali nazionali. Un primo test è stato effettuato nel 2023 nell'area della Communauté de Communes Vallée de Chamonix Mont-Blanc. A seguito della risposta positiva e dei risultati incoraggianti, lo strumento continuerà a essere implementato in tutto il dipartimento nel 2024. </p>
        <p><strong>Contesto del progetto :</strong></p>
        <p>Le montagne e le aree protette sono <strong>tanto rifugi</strong> per la biodiversità quanto luoghi dove i visitatori possono <strong>ricaricare</strong> le batterie.</p>
        <p>Purtroppo, la presenza massiccia e prolungata di escursionisti e bivaccatori sta contribuendo alla trasformazione duratura di questi ambienti naturali prima incontaminati. In alcune serate, i guardiani della riserva naturale hanno osservato picchi di fino a 120 tende sulle rive di un lago d'alta quota. </p>
        <p>Il numero di visitatori ha <strong>una serie di impatti</strong> sulle numerose specie rare e/o protette che vivono in queste riserve: l'inquinamento acustico, che provoca stress e modifica il comportamento; l'abbandono di rifiuti, i servizi igienici non autorizzati, le sostanze inquinanti nei fiumi e nei laghi, il disturbo degli habitat eccezionali, ecc.</p>
        <p>- <strong>Degrado del suolo</strong>: l'affluenza dei visitatori porta all'erosione dei sentieri e alla creazione di percorsi paralleli, che a volte richiedono importanti interventi di ripristino. I bivaccatori modificano il sito di bivacco per la notte per migliorare il loro comfort: il terreno viene livellato e le rocce spostate. Quindi, se ogni sera più di 250 persone (se prendiamo l'esempio di 120 tende) modificano l'ambiente per la notte, questo provoca gravi danni. </p>
        <p>- <strong>Disturbo della fauna selvatica</strong>: quando si fa un'escursione e si bivacca in un'area naturale protetta, si entra in un mondo fragile. Gli animali devono affrontare le dure condizioni di vita in alta montagna. I rumori e i disturbi causati dall'uomo <strong>sono vissuti come allarmi che potenzialmente</strong> innescano un ulteriore dispendio di energia per fuggire. Il disturbo porta anche al fallimento riproduttivo, in particolare quando le covate o i nidi vengono abbandonati.
        Anche una sola voce, un passaggio o una musica possono minacciare la sopravvivenza degli individui (uccelli, mammiferi). </p>
        <p>- <strong>La qualità dell'acqua di torrenti e laghi</strong>: rive calpestate da milioni di visitatori, creme solari, detersivi... tutto ciò ha un impatto irreparabile sui torrenti e sui laghi di montagna. L'acqua torbida compromette l'ossigenazione, vitale per gli organismi viventi che vengono indeboliti anche dagli agenti inquinanti.</p>
        <p>- <strong>Servizi igienici e rifiuti non autorizzati</strong>: Gli escrementi umani possono essere portatori di parassiti distruttivi. Contribuiscono inoltre all'inquinamento di fiumi e laghi. La decomposizione dei rifiuti, anche di quelli biodegradabili, è molto lenta. Una mela a 2000 metri di altitudine impiega diversi mesi per decomporsi. Questo interrompe l'intero ciclo biologico. </p>
        <p>Ammiriamo i fiori di montagna senza raccoglierli, camminiamo sui sentieri segnalati senza calpestare l'ambiente naturale circostante, chiudiamo i cancelli dei pascoli per rispettare il lavoro dei pastori.
        La natura è la nostra casa comune, uno spazio di vita per la biodiversità e gli animali, oltre che uno spazio di lavoro. Ogni gesto conta, quindi passate il messaggio al vostro vicino!</p>
        `
    }
});

export default about.reducer;
