import { createSlice } from "@reduxjs/toolkit";

export const infos = createSlice({
    name: "infos",
    initialState: {
        fr: {
            "elements": [
                {
                    "name": "date",
                    "type": "text",
                    "title": "Date du bivouac",
                    "inputType": "date",
                    "defaultValueExpression": "currentDate()",
                    "isRequired": true
                },
                {
                    "name": "nb_tents",
                    "type": "text",
                    "title": "Nombre de tentes",
                    "maxLength": 25,
                    "inputType": "number",
                    "min": 0,
                    "max": 100,
                    "defaultValue": 0,
                    "isRequired": true
                },
                {
                    "name": "nb_people",
                    "type": "text",
                    "title": "Nombre de personnes",
                    "maxLength": 25,
                    "inputType": "number",
                    "min": 1,
                    "max": 5,
                    "defaultValue": 1,
                    "isRequired": true
                },
                {
                    "name": "email",
                    "type": "text",
                    "title": "E-mail du déclarant",
                    "inputType": "email",
                    "placeholder": "foobar@example.com",
                    "isRequired": true,
                    "autocomplete": "email"
                },
                {
                    "name": "fr_or_foreign",
                    "type": "dropdown",
                    "title": "France ou étranger",
                    "maxLength": 25,
                    "isRequired": true,
                    "choices": [ "France", "Étranger" ]
                },
                {
                    "name": "department",
                    "type": "dropdown",
                    "title": "Département de résidence",
                    "maxLength": 25,
                    "isRequired": true,
                    "choices": [
                        "Haute-Savoie",
                        "Ain",
                        "Aisne",
                        "Allier",
                        "Alpes-de-Haute-Provence",
                        "Hautes-Alpes",
                        "Alpes-Maritimes",
                        "Ardèche",
                        "Ardennes",
                        "Ariège",
                        "Aube",
                        "Aude",
                        "Aveyron",
                        "Bouches-du-Rhône",
                        "Calvados",
                        "Cantal",
                        "Charente",
                        "Charente-Maritime",
                        "Cher",
                        "Corrèze",
                        "Côte-d'Or",
                        "Côtes-d'Armor",
                        "Creuse",
                        "Dordogne",
                        "Doubs",
                        "Drôme",
                        "Eure",
                        "Eure-et-Loir",
                        "Finistère",
                        "Corse-du-Sud",
                        "Haute-Corse",
                        "Gard",
                        "Haute-Garonne",
                        "Gers",
                        "Gironde",
                        "Hérault",
                        "Ille-et-Vilaine",
                        "Indre",
                        "Indre-et-Loire",
                        "Isère",
                        "Jura",
                        "Landes",
                        "Loir-et-Cher",
                        "Loire",
                        "Haute-Loire",
                        "Loire-Atlantique",
                        "Loiret",
                        "Lot",
                        "Lot-et-Garonne",
                        "Lozère",
                        "Maine-et-Loire",
                        "Manche",
                        "Marne",
                        "Haute-Marne",
                        "Mayenne",
                        "Meurthe-et-Moselle",
                        "Meuse",
                        "Morbihan",
                        "Moselle",
                        "Nièvre",
                        "Nord",
                        "Oise",
                        "Orne",
                        "Pas-de-Calais",
                        "Puy-de-Dôme",
                        "Pyrénées-Atlantiques",
                        "Hautes-Pyrénées",
                        "Pyrénées-Orientales",
                        "Bas-Rhin",
                        "Haut-Rhin",
                        "Rhône",
                        "Haute-Saône",
                        "Saône-et-Loire",
                        "Sarthe",
                        "Savoie",
                        "Haute-Savoie",
                        "Paris",
                        "Seine-Maritime",
                        "Seine-et-Marne",
                        "Yvelines",
                        "Deux-Sèvres",
                        "Somme",
                        "Tarn",
                        "Tarn-et-Garonne",
                        "Var",
                        "Vaucluse",
                        "Vendée",
                        "Vienne",
                        "Haute-Vienne",
                        "Vosges",
                        "Yonne",
                        "Territoire de Belfort",
                        "Essonne",
                        "Hauts-de-Seine",
                        "Seine-Saint-Denis",
                        "Val-de-Marne",
                        "Val-d'Oise",
                        "Guadeloupe",
                        "Martinique",
                        "Guyane",
                        "La Réunion",
                        "Mayotte"
                        ],
                    "visibleIf": "{fr_or_foreign} = France",
                },
                {
                    "name": "itinerance",
                    "type": "boolean",
                    "title": "Option en itinérance",
                    "maxLength": 25,
                    "isRequired": true,
                    "valueTrue": "Yes",
                    "valueFalse": "No"
                }
            ],
            "showQuestionNumbers": false
        },
        en: {
            "elements": [
                {
                    "name": "date",
                    "type": "text",
                    "title": "Date of bivouac",
                    "inputType": "date",
                    "defaultValueExpression": "currentDate()",
                    "isRequired": true
                },
                {
                    "name": "nb_tents",
                    "type": "text",
                    "title": "Number of tents",
                    "maxLength": 25,
                    "inputType": "number",
                    "min": 0,
                    "max": 100,
                    "defaultValue": 0,
                    "isRequired": true
                },
                {
                    "name": "nb_people",
                    "type": "text",
                    "title": "Number of people",
                    "maxLength": 25,
                    "inputType": "number",
                    "min": 1,
                    "max": 5,
                    "defaultValue": 1,
                    "isRequired": true
                },
                {
                    "name": "email",
                    "type": "text",
                    "title": "E-mail address of the declarant",
                    "inputType": "email",
                    "placeholder": "foobar@example.com",
                    "isRequired": true,
                    "autocomplete": "email"
                },
                {
                    "name": "fr_or_foreign",
                    "type": "dropdown",
                    "title": "France or foreign",
                    "maxLength": 25,
                    "isRequired": true,
                    "choices": [ "France", "Foreign" ]
                },
                {
                    "name": "department",
                    "type": "dropdown",
                    "title": "Department of residence",
                    "maxLength": 25,
                    "isRequired": true,
                    "choices": [
                        "Haute-Savoie",
                        "Ain",
                        "Aisne",
                        "Allier",
                        "Alpes-de-Haute-Provence",
                        "Hautes-Alpes",
                        "Alpes-Maritimes",
                        "Ardèche",
                        "Ardennes",
                        "Ariège",
                        "Aube",
                        "Aude",
                        "Aveyron",
                        "Bouches-du-Rhône",
                        "Calvados",
                        "Cantal",
                        "Charente",
                        "Charente-Maritime",
                        "Cher",
                        "Corrèze",
                        "Côte-d'Or",
                        "Côtes-d'Armor",
                        "Creuse",
                        "Dordogne",
                        "Doubs",
                        "Drôme",
                        "Eure",
                        "Eure-et-Loir",
                        "Finistère",
                        "Corse-du-Sud",
                        "Haute-Corse",
                        "Gard",
                        "Haute-Garonne",
                        "Gers",
                        "Gironde",
                        "Hérault",
                        "Ille-et-Vilaine",
                        "Indre",
                        "Indre-et-Loire",
                        "Isère",
                        "Jura",
                        "Landes",
                        "Loir-et-Cher",
                        "Loire",
                        "Haute-Loire",
                        "Loire-Atlantique",
                        "Loiret",
                        "Lot",
                        "Lot-et-Garonne",
                        "Lozère",
                        "Maine-et-Loire",
                        "Manche",
                        "Marne",
                        "Haute-Marne",
                        "Mayenne",
                        "Meurthe-et-Moselle",
                        "Meuse",
                        "Morbihan",
                        "Moselle",
                        "Nièvre",
                        "Nord",
                        "Oise",
                        "Orne",
                        "Pas-de-Calais",
                        "Puy-de-Dôme",
                        "Pyrénées-Atlantiques",
                        "Hautes-Pyrénées",
                        "Pyrénées-Orientales",
                        "Bas-Rhin",
                        "Haut-Rhin",
                        "Rhône",
                        "Haute-Saône",
                        "Saône-et-Loire",
                        "Sarthe",
                        "Savoie",
                        "Haute-Savoie",
                        "Paris",
                        "Seine-Maritime",
                        "Seine-et-Marne",
                        "Yvelines",
                        "Deux-Sèvres",
                        "Somme",
                        "Tarn",
                        "Tarn-et-Garonne",
                        "Var",
                        "Vaucluse",
                        "Vendée",
                        "Vienne",
                        "Haute-Vienne",
                        "Vosges",
                        "Yonne",
                        "Territoire de Belfort",
                        "Essonne",
                        "Hauts-de-Seine",
                        "Seine-Saint-Denis",
                        "Val-de-Marne",
                        "Val-d'Oise",
                        "Guadeloupe",
                        "Martinique",
                        "Guyane",
                        "La Réunion",
                        "Mayotte"
                        ],
                    "visibleIf": "{fr_or_foreign} = France",
                },
                {
                    "name": "itinerance",
                    "type": "boolean",
                    "title": "Roaming option",
                    "maxLength": 25,
                    "isRequired": true,
                    "valueTrue": "Yes",
                    "valueFalse": "No"
                }
            ],
            "showQuestionNumbers": false
        },
        it: {
            "elements": [
                {
                    "name": "date",
                    "type": "text",
                    "title": "Data del bivacco",
                    "inputType": "date",
                    "defaultValueExpression": "currentDate()",
                    "isRequired": true
                },
                {
                    "name": "nb_tents",
                    "type": "text",
                    "title": "Numero di tende",
                    "maxLength": 25,
                    "inputType": "number",
                    "min": 0,
                    "max": 100,
                    "defaultValue": 0,
                    "isRequired": true
                },
                {
                    "name": "nb_people",
                    "type": "text",
                    "title": "Numero di persone",
                    "maxLength": 25,
                    "inputType": "number",
                    "min": 1,
                    "max": 5,
                    "defaultValue": 1,
                    "isRequired": true
                },
                {
                    "name": "email",
                    "type": "text",
                    "title": "Indirizzo e-mail del dichiarante",
                    "inputType": "email",
                    "placeholder": "foobar@example.com",
                    "isRequired": true,
                    "autocomplete": "email"
                },
                {
                    "name": "fr_or_foreign",
                    "type": "dropdown",
                    "title": "Francia o all'estero",
                    "maxLength": 25,
                    "isRequired": true,
                    "choices": [ "Francia", "All'estero" ]
                },
                {
                    "name": "department",
                    "type": "dropdown",
                    "title": "Dipartimento di residenza",
                    "maxLength": 25,
                    "isRequired": true,
                    "choices": [
                        "Haute-Savoie",
                        "Ain",
                        "Aisne",
                        "Allier",
                        "Alpes-de-Haute-Provence",
                        "Hautes-Alpes",
                        "Alpes-Maritimes",
                        "Ardèche",
                        "Ardennes",
                        "Ariège",
                        "Aube",
                        "Aude",
                        "Aveyron",
                        "Bouches-du-Rhône",
                        "Calvados",
                        "Cantal",
                        "Charente",
                        "Charente-Maritime",
                        "Cher",
                        "Corrèze",
                        "Côte-d'Or",
                        "Côtes-d'Armor",
                        "Creuse",
                        "Dordogne",
                        "Doubs",
                        "Drôme",
                        "Eure",
                        "Eure-et-Loir",
                        "Finistère",
                        "Corse-du-Sud",
                        "Haute-Corse",
                        "Gard",
                        "Haute-Garonne",
                        "Gers",
                        "Gironde",
                        "Hérault",
                        "Ille-et-Vilaine",
                        "Indre",
                        "Indre-et-Loire",
                        "Isère",
                        "Jura",
                        "Landes",
                        "Loir-et-Cher",
                        "Loire",
                        "Haute-Loire",
                        "Loire-Atlantique",
                        "Loiret",
                        "Lot",
                        "Lot-et-Garonne",
                        "Lozère",
                        "Maine-et-Loire",
                        "Manche",
                        "Marne",
                        "Haute-Marne",
                        "Mayenne",
                        "Meurthe-et-Moselle",
                        "Meuse",
                        "Morbihan",
                        "Moselle",
                        "Nièvre",
                        "Nord",
                        "Oise",
                        "Orne",
                        "Pas-de-Calais",
                        "Puy-de-Dôme",
                        "Pyrénées-Atlantiques",
                        "Hautes-Pyrénées",
                        "Pyrénées-Orientales",
                        "Bas-Rhin",
                        "Haut-Rhin",
                        "Rhône",
                        "Haute-Saône",
                        "Saône-et-Loire",
                        "Sarthe",
                        "Savoie",
                        "Haute-Savoie",
                        "Paris",
                        "Seine-Maritime",
                        "Seine-et-Marne",
                        "Yvelines",
                        "Deux-Sèvres",
                        "Somme",
                        "Tarn",
                        "Tarn-et-Garonne",
                        "Var",
                        "Vaucluse",
                        "Vendée",
                        "Vienne",
                        "Haute-Vienne",
                        "Vosges",
                        "Yonne",
                        "Territoire de Belfort",
                        "Essonne",
                        "Hauts-de-Seine",
                        "Seine-Saint-Denis",
                        "Val-de-Marne",
                        "Val-d'Oise",
                        "Guadeloupe",
                        "Martinique",
                        "Guyane",
                        "La Réunion",
                        "Mayotte"
                        ],
                    "visibleIf": "{fr_or_foreign} = Francia",
                },
                {
                    "name": "itinerance",
                    "type": "boolean",
                    "title": "Opzione roaming",
                    "maxLength": 25,
                    "isRequired": true,
                    "valueTrue": "Yes",
                    "valueFalse": "No"
                }
            ],
            "showQuestionNumbers": false
        }
    }
});

export default infos.reducer;
